### ISSUE TITLE
大英3

### ISSUE THREAD

**Issue by XuandYu000** [superpung/TJU-CourseSharing#16]
[19201大英3真题.pdf](https://github.com/superpung/TJU-CourseSharing/files/11003598/19201.3.pdf)
[天津大学《大学英语3》2021-2022学年第一学期期末试卷B卷.pdf](https://github.com/superpung/TJU-CourseSharing/files/11003600/3.2021-2022.B.pdf)

**Comment by superpung** [comment]
Thank you for contributing, and I'll add these files later.
